### ISSUE TITLE
Reading waypoints-public.js

### ISSUE THREAD

**Issue by tamielbr** [scholarslab/NeatlineWaypoints#1]
Hi, we are trying to customize the pop-up when clicking on a NeatlineWaypoints element, and it points to waypoints-public.js. 

We are specifically trying to customize (add info) or remove the "title" pop-up which shows "on mouse over" the waypoint list (it seems redundant). 

The file we see in our server is differen from the one on github. 'm assuming it processed somehow, but we're not knowledgeable enough. 

We ended up removing the "mouserenter" "mouseleave" line and it worked, but we're wondering how to contribute this and any customization ideas appropriately. Thanks!

**Comment by waynegraham** [comment]
@tamielbr Sorry, just saw this...The files are compressed and concatenated using Grunt tasks (defined in the [Gruntfile](https://github.com/scholarslab/nl-widget-Waypoints/blob/master/Gruntfile.js). If you fork this repository and send a pull request, we can take a look at your fork.

**Comment by tamielbr** [comment]
@gabrielfedel, we should take a look at doing this; we forgot.

**Comment by jeremyboggs** [comment]
@tamielbr Am closing this, assuming @waynegraham's response helped you out. But if you need more help, get in touch!
