### ISSUE TITLE
Error in Internet Explorer

### ISSUE THREAD

**Issue by EmilyMarsh-USDA** [scholarslab/NeatlineWaypoints#4]
Hello:

I have a Neatline exhibit using Waypoints within a larger Omeka instance (http://theillustratedword.com/neatline/fullscreen/the-frost-farm).

It works properly in every browser except IE.

When I click on a waypoint title, the corresponding record does not appear.

The IE debugger reports the following after line 482 in the neatline-public.js file:

```
                }
                if (p)
                    try  {
                        return _.apply(c, o.querySelectorAll(p)), c;
```

SyntaxError
                        } catch (q) {
                        } finally {
                            l || b.removeAttribute("id");
                        }
                }

Each record will appear if I reload the file, but that is not really a solution.

Is there anything I could do to correct this?

Thanks!
Emily

**Comment by waynegraham** [comment]
Hi @EmilyMarsh,

What version of IE are you seeing this on? It'll help us figure out what's going on for IE.

Wayne

**Comment by EmilyMarsh-USDA** [comment]
Hi @waynegraham:

Thanks so much for your fast response.

It's the most current version:
11.0.9600.17420.

Emily

**Comment by EmilyMarsh-USDA** [comment]
I am using Omeka 2.2.2, Neatline 2.3.0, and Waypoints 2.0.2

**Comment by davidmcclure** [comment]
Hey @EmilyMarsh,

First of all, that is a very cool exhibit! Love the combination a static image background and the point-image overlays. As for this IE bug - I just pushed up a little change that I think might fix the problem. I'm not sure, since I don't have easy access to a computer with IE on it, but I've got a hunch. Click this link to download a .zip archive with the change:

https://github.com/scholarslab/nl-widget-Waypoints/archive/bug/ie11.zip

When you uncompress the file, you'll get a folder called `nl-widget-Waypoints-bug-ie11`. Rename this to just `NeatlineWaypoints`, and copy it into your Omeka plugins folder. Then, fire up the browser and see if the problem is still there.

If so, could you paste in the full stack trace from the IE console? In this version, I bundled in the uncompressed version Javascript payload, which means that the stack trace will include much more precise information about where exactly the problem is.

Thanks!
David

**Comment by EmilyMarsh-USDA** [comment]
Hi @davidmcclure:

Thank you so much for the compliment <em>and</em> the code!

I will follow your instructions and report what I find.

Emily

**Comment by EmilyMarsh-USDA** [comment]
@davidmcclure:

The same error occurs: the wayppoint titles appear, but remain unresponsive.

The entire js file is too long to paste here.

Will this provide enough information?

![neatlinewaypointerror](https://cloud.githubusercontent.com/assets/5777982/5079400/14f3920c-6e82-11e4-84e5-9e262dcf8c91.jpg)

The same error occurs for every instance of clinking on a title: right after line 410982.

I am sorry if I am misunderstanding what you need to debug this.

Let me know if I need to give you something else and I will do my best to provide it.

Emily

**Comment by davidmcclure** [comment]
Ok cool, try clicking on the little icon with the square and the right-facing carrot thingy, in the vertical pane on the left. Do you see a big stack of error output?

**Comment by EmilyMarsh-USDA** [comment]
I apologize for bringing you to a place where you have to write, "the little icon with the square and the right-facing carrot thingy."

Anyway, after clicking on said icon, there is nothing. 

![errormessage](https://cloud.githubusercontent.com/assets/5777982/5080666/5932f7fa-6e91-11e4-9ac5-21c25cbf1296.jpg)

**Comment by waynegraham** [comment]
@davidmcclure I haven't gotten this set up, but Microsoft is letting folks run IE on Azure (see https://remote.modern.ie/). You can also grab VMs for various combinations of Windows at https://www.modern.ie/en-us/virtualization-tools. I'm still trying to figure out the dev tools to get the console open, but worse case I'll find a windows machine tomorrow...

**Comment by davidmcclure** [comment]
@EmilyMarsh Ha, no worries, I just couldn't think up a better name for it :) Thanks for the links, Wayne, I'll take a look tomorrow.

**Comment by waynegraham** [comment]
@davidmcclure In Windows 10 with IE 11.0.8, no errors are thrown and it works as expected. I'm hunting down a Windows 7 machine...

**Comment by EmilyMarsh-USDA** [comment]
@waynegraham:

For what it's worth, I am running Windows 7.

I really appreciate all the effort you are putting into this.

Emily

**Comment by waynegraham** [comment]
In IE edge on Windows 7, I'm actually seeing this throw an error on `neatline-public.js` (SCRIPT87: Invalid argument. File: neatline-public, Line: 38, Column: 23456). It looks like it's an unhandled exception. When I turned off the break on exception setting, it still threw the error in the console, but would actually load the record.

@EmilyMarsh just to check this, if you click on the Debugger (the bug thing) you should see a hexagon with a pause symbol in it with a drop down. If you click on "Never break on exceptions" and then reload the page, do you still see the behavior?

**Comment by EmilyMarsh-USDA** [comment]
If I set it on "Never break on exceptions," it enters a loop and never opens the record. It doesn't even seem to recognize the waypoint title as a link.

The error report stays the same for every step in the loop:

![neverbreak1](https://cloud.githubusercontent.com/assets/5777982/5089057/57cc7812-6f06-11e4-9178-9a374caf0d7a.jpg)

And the Console is blank:

![neverbreak2](https://cloud.githubusercontent.com/assets/5777982/5089062/650d553c-6f06-11e4-9d0c-d0cbaecfbe90.jpg)

**Comment by waynegraham** [comment]
@davidmcclure What do you think about adding source maps to the JavaScript build? I just pushed a change that generates source maps in `uglify` so we can figure out which function `b` maps to :)

@EmilyMarsh is this a production server, or something we can try something on? If we can try something, could you replace your version of the Neatline plugin with https://github.com/scholarslab/Neatline/archive/feature/sourcemap.zip? Or, clone the repo with something like this?

```
$ cd path/to/omeka/plugins
$ mv Neatline ~/ 
$ git clone https://github.com/scholarslab/Neatline.git
$ cd Neatline
$ git checkout feature/sourcemap
```

This is based off the version we were hoping to release today, so it has some new features, but we want to be sure there's not a lingering bug...

If this is a production system, we can figure out something else...

**Comment by EmilyMarsh-USDA** [comment]
@waynegraham and @davidmcclure:

This is my own public-facing site that is sorta turning into a development site for the final version that is tucked away from public view.

So, we can hack away at theillustratedword.com.

I will replace the Neatline plugin with the resource above, but I will need about 45 minutes or so.

Thanks, Emily

**Comment by EmilyMarsh-USDA** [comment]
OK--I am doing something wrong.

I deleted my old Neatine plugin folder and moved in the new one linked above, but Omeka now does not recognize this as a plugin.

Help?

**Comment by EmilyMarsh-USDA** [comment]
@waynegraham and @davidmcclure:

I changed the name of your folder from Neatline-feature-sourcemap to just Neatline. Could that have caused the failure?

**Comment by davidmcclure** [comment]
@EmilyMarsh yeah, that was the problem. Omeka loads code for plugins by looking for a folder that matches the name in the database (just plain `Neatline`), so the .zip archives from GitHub (which add the branch name to the end) will throw things off.

I just checked this out in the Azure remote desktop, on IE 11.0.9879.0, and can't reproduce the problem - console is clean, and the debugger doesn't show anything. Working from the code that's visible in the screenshot, though, it looks like the problem has something to do with the [Rivets](https://github.com/mikeric/rivets) library that we use to do two-way bindings between the Backbone models and the templates. Let me read around a little more and see if I can find anything suspicious. Thanks for helping us get to the bottom of this!

**Comment by waynegraham** [comment]
@EmilyMarsh is this a theme you created? I noticed an extra `</script>` on the page which is the first thing IE is complaining about. Could you try switching themes real fast to test if this is the culprit (ThanksRoy should work).

**Comment by EmilyMarsh-USDA** [comment]
I used the Deco theme. Deco allows for background images--maybe that is causing a problem. (If you look at the main site at theillustratedword.com you can see the background image of a red fence that is actually sitting behind the map in the Neatline exhibit. Since I am only using the historical map as an image, I didn't think the presence or absence of a background would make any difference.)

I just tested the page with ThanksRoy in IE and have the same problem.

I have inserted a message to encourage users to not use IE. I am considering creating a simple page to stand in front of the Neatline exhibit with a more obvious warning.

**Comment by EmilyMarsh-USDA** [comment]
Hi @waynegraham: 

I was able to install and activate your replacement plugin, but it makes the Neatline exhibit crash and throw a 404 error.

Emily

**Comment by waynegraham** [comment]
In the Omeka admin for plugins, did you click the upgrade button? When you say crash the exhibit, is it crashing the browser, or the admin interface doesn't show the Neatline plugin anymore?

**Comment by EmilyMarsh-USDA** [comment]
When I installed your new version (Neatline 2) it showed up as a plugin called "Neatline." (I had already deactivated the original Neatline (Neatline 1)) When I activated the Neatline 2 plugin, I got a 404 page when I tried to access the Neatline exhibit ("Frost's Farm.").

I have since deactivated and uninstalled Neatline 2.

When I re-activated Neatline 1, the exhibit does not show in the admin interface and, of course, results in a 404 page in the public site.

I just restored the exhibit from a backup.

**Comment by waynegraham** [comment]
Can you make a database dump (temporarily) available? This gist should help:

https://gist.github.com/waynegraham/5493609839a596f279c4

If you'll send me the path at wayne dot graham at virginia dot edu I'll get that straightened out.

**Comment by EmilyMarsh-USDA** [comment]
I'm sorry, Wayne.

I think we have reached the admittedly low ceiling of my technical skills. : )

I don't understand what you want. Can you clarify?

My site is back, so that is all good.

**Comment by waynegraham** [comment]
Sorry about that :) Could I get a copy of your database (or at least the Neatline tables)? It's a little difficult to troubleshoot right now with us making small adjustments around IE and asking you to constantly update. I'm not sure of your server setup, but if you add that script to the PATH (or save it in the directory with the `db.ini` file in it), it'll create a snapshot of your database. If you move that in to a location that is accessible to the web (like omeka/files/original) and email me that path, I can grab it and we can _hopefully_ move a bit faster on this.

**Comment by EmilyMarsh-USDA** [comment]
email sent

**Comment by EmilyMarsh-USDA** [comment]
Hi @waynegraham:

Any luck?

Emily

**Comment by waynegraham** [comment]
Not yet; we're starting to think there may be an issue with the underlying library we're using getting the data to Neatline. We're working on isolating the problem to fully understand what's going on and how IE is processing the structures to get a permanent fix in place so this doesn't pop up in future versions of IE.

**Comment by EmilyMarsh-USDA** [comment]
Thanks for the update; I really appreciate it.

Emily
